
package com.renovelabz.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FrameBuffer", targetNamespace = "http://server.renovelabz.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FrameBuffer {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSegmentID", targetNamespace = "http://server.renovelabz.com/", className = "com.renovelabz.server.GetSegmentID")
    @ResponseWrapper(localName = "getSegmentIDResponse", targetNamespace = "http://server.renovelabz.com/", className = "com.renovelabz.server.GetSegmentIDResponse")
    @Action(input = "http://server.renovelabz.com/FrameBuffer/getSegmentIDRequest", output = "http://server.renovelabz.com/FrameBuffer/getSegmentIDResponse")
    public int getSegmentID();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.renovelabz.server.FramePullResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pullFrames", targetNamespace = "http://server.renovelabz.com/", className = "com.renovelabz.server.PullFrames")
    @ResponseWrapper(localName = "pullFramesResponse", targetNamespace = "http://server.renovelabz.com/", className = "com.renovelabz.server.PullFramesResponse")
    @Action(input = "http://server.renovelabz.com/FrameBuffer/pullFramesRequest", output = "http://server.renovelabz.com/FrameBuffer/pullFramesResponse")
    public FramePullResult pullFrames(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pushFrame", targetNamespace = "http://server.renovelabz.com/", className = "com.renovelabz.server.PushFrame")
    @ResponseWrapper(localName = "pushFrameResponse", targetNamespace = "http://server.renovelabz.com/", className = "com.renovelabz.server.PushFrameResponse")
    @Action(input = "http://server.renovelabz.com/FrameBuffer/pushFrameRequest", output = "http://server.renovelabz.com/FrameBuffer/pushFrameResponse")
    public int pushFrame(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "startNewSegment", targetNamespace = "http://server.renovelabz.com/", className = "com.renovelabz.server.StartNewSegment")
    @ResponseWrapper(localName = "startNewSegmentResponse", targetNamespace = "http://server.renovelabz.com/", className = "com.renovelabz.server.StartNewSegmentResponse")
    @Action(input = "http://server.renovelabz.com/FrameBuffer/startNewSegmentRequest", output = "http://server.renovelabz.com/FrameBuffer/startNewSegmentResponse")
    public void startNewSegment();

}
