
package com.renovelabz.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FrameBufferImplService", targetNamespace = "http://server.renovelabz.com/", wsdlLocation = "http://localhost:8000/screenrelay?wsdl")
public class FrameBufferImplService
    extends Service
{

    private final static URL FRAMEBUFFERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FRAMEBUFFERIMPLSERVICE_EXCEPTION;
    private final static QName FRAMEBUFFERIMPLSERVICE_QNAME = new QName("http://server.renovelabz.com/", "FrameBufferImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/screenrelay?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FRAMEBUFFERIMPLSERVICE_WSDL_LOCATION = url;
        FRAMEBUFFERIMPLSERVICE_EXCEPTION = e;
    }

    public FrameBufferImplService() {
        super(__getWsdlLocation(), FRAMEBUFFERIMPLSERVICE_QNAME);
    }

    public FrameBufferImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FRAMEBUFFERIMPLSERVICE_QNAME, features);
    }

    public FrameBufferImplService(URL wsdlLocation) {
        super(wsdlLocation, FRAMEBUFFERIMPLSERVICE_QNAME);
    }

    public FrameBufferImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FRAMEBUFFERIMPLSERVICE_QNAME, features);
    }

    public FrameBufferImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FrameBufferImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FrameBuffer
     */
    @WebEndpoint(name = "FrameBufferImplPort")
    public FrameBuffer getFrameBufferImplPort() {
        return super.getPort(new QName("http://server.renovelabz.com/", "FrameBufferImplPort"), FrameBuffer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FrameBuffer
     */
    @WebEndpoint(name = "FrameBufferImplPort")
    public FrameBuffer getFrameBufferImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.renovelabz.com/", "FrameBufferImplPort"), FrameBuffer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FRAMEBUFFERIMPLSERVICE_EXCEPTION!= null) {
            throw FRAMEBUFFERIMPLSERVICE_EXCEPTION;
        }
        return FRAMEBUFFERIMPLSERVICE_WSDL_LOCATION;
    }

}
